include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_final_locals
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - prefer_single_quotes
